# Generated by Django 4.1.4 on 2022-12-13 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0003_movieorder"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movieorder",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
